### ISSUE TITLE
plot function change request checklist

### ISSUE THREAD

**Issue by sgaichas** [NOAA-EDAB/ecodata#130]
We can keep a running list here as we see them:

- [x] `plot_hms_stock_status` - recolor points so that anything below Bmsy or above Fmsy is the not meeting objectives color (orange), everything above Bmsy and below Fmsy is green, there is no purple
- [x] `plot_species_dist` - returns an error when NewEngland is called. Maybe it should return text. fro example: "Same as Mid Atlantic" or "this is a shelfwide indcator" or "this is present in the mid atlantic report only"

See also other plot related issues

- [x] https://github.com/NOAA-EDAB/ecodata/issues/127
- [x] https://github.com/NOAA-EDAB/ecodata/issues/119
